title: Usha Nanthini
logo: /assets/img/logo.png
description: I am a data engineer with 5+ years of experience in Oracle PLSQL domain. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
